### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by f33r0** [fewensa/subquery-cli#7]
Hello, we are getting an error.
15:04:40 + /home/ubuntu/.local/bin/subquery --token **** deployment deploy --org org --key key --branch branch --type stage --indexer-image-version v0.31.1 --query-image-version v0.13.0 --endpoint wss://endpoint --force
15:04:43 Custom: Not have git repository url for project

**Comment by fewensa** [comment]
If your subql project deploy by git repository, please create first.
https://github.com/fewensa/subquery-cli#create-a-project

then deploy follow this
https://github.com/fewensa/subquery-cli#deploy
